NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
SQ02_EASTER_EGG="Log into series 2 of Stellar Quest then visit quest.stellar.org/series2. Finally drag and drop your Stellar Quest series 2 badge PNG images onto the screen. Enjoy!"
ACCOUNTS=[
"GDUDV56OWZYQ7Y333NZU2VAO7JM5X5ORFCDOEHUPXVJZK325TXPND37I",
"GBIRU3F4ZQMWX3FQITH62XBA2YHFNDXVXFOYB6QTCB3UUFVQW2YQJ433"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="silence48"
ORG_URL="https://www.domain.com"
ORG_LOGO="https://silence48.github.io/image.jpg"
ORG_DESCRIPTION="The silence48 org"
ORG_PHYSICAL_ADDRESS="123 Sesame Street, New York, NY 12345, United States"

[[PRINCIPALS]]
name="Silence48"
email="35656692+silence48@users.noreply.github.com"
keybase="silence48"
twitter="silence48"
github="silence48"

[[CURRENCIES]]
code="silence"
issuer="GDUDV56OWZYQ7Y333NZU2VAO7JM5X5ORFCDOEHUPXVJZK325TXPND37I"
display_decimals=8
name="silence"
desc="The silence Token"
conditions="This is test software"

